# ?? Server ??
quarkus.http.port=8081

# ?? REST Client : Clipper (Spring Boot sur le port 8080) ??
quarkus.rest-client.clipper-api.url=http://localhost:8080

# ?? Hibernate ORM ??
# Dev Services demarre PostgreSQL automatiquement, aucune URL/user/password a configurer
quarkus.hibernate-orm.schema-management.strategy=drop-and-create
quarkus.datasource.db-kind=postgresql

# ?? Securite : Basic Auth ??
quarkus.http.auth.basic=true